export const metadata = {
  title: "Gilbard",
  description: "Generated by Sohaib, create in Next.JS",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        {children}
      </body>
    </html>
  );
}
